#!/bin/bash

# Install Kind
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind

# Install kubectl (fixed version)
VERSION="v1.30.0"
curl -LO "https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl"
chmod +x kubectl
sudo mv kubectl /usr/local/bin/kubectl

# Verify
kind --version
kubectl version --client

# Cleanup
rm -f kind
rm -f kubectl

echo "✅ Kind & kubectl installation complete"
